image: registry.gitlab.com/bouldersky/cubetrainer

before_script:
  - flutter pub get

pages:
  stage: deploy
  script:
    - mv web/index_gitlab.html web/index.html
    - flutter build web
    - cp -r build/web public
  artifacts:
    paths:
      - public
  only:
    - master