stages:
  - deploy
  - alert

pages:
  stage: deploy
  image: registry.gitlab.com/bouldersky/cubetrainer
  script:
    - flutter pub get
    - mv web/index_gitlab.html web/index.html
    - flutter build web
    - cp -r build/web public
  artifacts:
    paths:
      - public
  only:
    - master

script:
  stage: alert
  image: ubuntu:latest
  script:
    - apt update -y
    - apt install -y curl
    - > 
      curl -v -X POST 
      https://discordapp.com/api/webhooks/811820976710221874/JJLbx-N1e07cXN9waPALEJxN7FVH1LEEC9_8pCo9KQfbfJFJIO6tHFI6aslFe9H2A26V
      -H "Content-Type: application/json" 
      --data '{"content": "New Cube Trainer version has been deployed!"}'
  only:
    - master